networks:
  nginx-net:
    external:
      name: nginx-net


services:
  frontend:
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: "${NGINX_SERVER_NAME}"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "${NGINX_SERVER_NAME}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    env_file:
      - .env
    ports:
      - ${FRONTEND_PUBLIC_PORT}:80
    networks:
      - nginx-net
